# Generated by Django 5.2.17 on 2026-08-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.CharField(choices=[('Asia', 'Asia'), ('Europe', 'Europe'), ('North America', 'North America'), ('South America', 'South America'), ('Africa', 'Africa'), ('Australia', 'Australia'), ('Antarctica', 'Antarctica')], max_length=30),
        ),
    ]
