# Generated by Django 5.2.17 on 2026-08-09 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.city', verbose_name='Cart Location'),
        ),
    ]
