"""
Django settings for studio_mathri project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pzlk^m3k9xzgm*_5d%baryr+97^=dvmshj(mu(asn=8m0^ap+p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    "jazzmin",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "dashboard",
    "countries",
    "states",
    "cities",
    "areas",
    "companies",
    "categories",
    "products",
    "analytics",
    "cart",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'studiomathri.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [BASE_DIR / "templates"],
        'APP_DIRS': True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "dashboard.context_processors.dashboard_stats",
                "dashboard.context_processors.cart_context",
            ],
        },
    },
]

WSGI_APPLICATION = 'studiomathri.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
JAZZMIN_SETTINGS = {

    "search_model": None,

    "site_title": "Studio Mathri Admin",
    "site_header": "Studio Mathri",
    "site_brand": "Studio Mathri",
    "welcome_sign": "Welcome to Studio Mathri Admin Panel",
    "copyright": "Studio Mathri",

    # SINGLE GLOBAL SEARCH: Faqt eka main model sathi search bar theva (e.g. Products)
    "search_model": "products.Product", 
    
    # Kiwa search bar poorna kadhaycha asel tr [] kara:
    # "search_model": [],

    "topmenu_links": [
        {
            "name": "Dashboard",
            "url": "admin:index",
            "permissions": ["auth.view_user"],
        },
    ],

    "show_sidebar": True,
    "navigation_expanded": True,

    "order_with_respect_to": [
        "countries", "countries.country",
        "states", "states.state",
        "cities", "cities.city",
        "areas", "areas.area",
        "companies", "companies.company",
        "categories", "categories.category",
        "products", "products.product",
        "cart","cart.cart",
        "auth", "auth.user", "auth.group",
    ],

    "icons": {
        "countries": "fas fa-globe",
        "countries.country": "fas fa-globe",
        "states": "fas fa-map",
        "states.state": "fas fa-map",
        "cities": "fas fa-city",
        "cities.city": "fas fa-city",
        "areas": "fas fa-location-dot",
        "areas.area": "fas fa-location-dot",
        "companies": "fas fa-building",
        "companies.company": "fas fa-building",
        "categories": "fas fa-layer-group",
        "categories.category": "fas fa-layer-group",
        "products": "fas fa-box-open",
        "products.product": "fas fa-box-open",
        "cart.cart": "fas fa-shopping-cart",
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.group": "fas fa-user-shield",
    
    },

    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",

    "show_ui_builder": False,
    "custom_css": "css/admin_custom.css",
    "custom_js": "js/admin_theme.js",
}
JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",
    "dark_mode_theme": "darkly",
}

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
